#!/bin/bash
#odczytanie wersji systemu
lsb_release -a >> "wersjasystemu.$(date +"%Y%m%d:%T")"
#odczytanie wersji jądra
uname -a >> "wersjakernela.$(date +"%Y%m%d:%T")"
#lista uzytkownikow
getent passwd >> "uzytkownicy.$(date +"%Y%m%d:%T")"
#lista grup
getent group | cut -d: -f1 | sort | cat -n >>"grupy.$(date +"%Y%m%d:%T")"
#lista interfejsów sieciowych
ip link show >>"interfejsysieciowe.$(date +"%Y%m%d:%T")"
#wykaz działających procesów
ps -aux >>"procesy1.$(date +"%Y%m%d:%T")"
#wykaz działających procesów 2
ps -A >>"procesy.$(date +"%Y%m%d:%T")"
#usługi sieciowe
ss -a -p >>"uslugisieciowe.$(date +"%Y%m%d:%T")"
#firewall
iptables -L>>"firewall.$(date +"%Y%m%d:%T")"
#zajetość dysku
df -h >>"punktymontowania.$(date +"%Y%m%d:%T")"
#punkty montownia
mount >>"punktymontowania1.$(date +"%Y%m%d:%T")"







